#version: '3.8'

services:
  venturepulse:
    build: .
    container_name: venturepulse
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
      - ./.env:/app/.env:ro
      - ./public:/app/public:ro
      - ./server.js:/app/server.js:ro
    environment:
      - NODE_ENV=production
      - PORT=8888
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
